import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

group = "net.rykosoft"
version = "0.1"

plugins {
    java

    application
    kotlin("jvm") version "1.2.71"
}

application {
    mainClassName = "net.rykosoft.builder.App"
}

dependencies {
    testCompile("junit:junit:4.12")
    compile(kotlin("stdlib-jdk8"))
}

repositories {
    jcenter()
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
